# Generated by Django 4.2.9 on 2024-01-31 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Author Model',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('date_of_pub', models.DateField()),
                ('genre', models.CharField(choices=[('horror', 'horror'), ('self help', 'self help'), ('adventure', 'adventure'), ('others', 'others')], default='others', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.author')),
            ],
            options={
                'verbose_name': 'Book Model',
                'ordering': ['-date_of_pub'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Profile Model',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('address', models.TextField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Publisher Model',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('book', models.ManyToManyField(to='store.book')),
            ],
            options={
                'verbose_name': 'Collection Model',
                'db_table': 'book_collection',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='store.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('author', 'title', 'date_of_pub')},
        ),
    ]
